// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketTrackerAPI.Models;

namespace TicketTrackerAPI.Migrations
{
    [DbContext(typeof(TicketTrackerContext))]
    [Migration("20190320062716_MyFirstMigration")]
    partial class MyFirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TicketTrackerAPI.Models.Ticketmaster", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClientName")
                        .HasMaxLength(50);

                    b.Property<string>("Description")
                        .HasColumnName("DEscription")
                        .HasMaxLength(500);

                    b.Property<string>("DeveloperName")
                        .HasMaxLength(50);

                    b.Property<string>("Module")
                        .HasMaxLength(50);

                    b.Property<int?>("Priority")
                        .HasColumnName("priority");

                    b.Property<string>("ShortNotes")
                        .HasMaxLength(50);

                    b.HasKey("TicketId");

                    b.ToTable("Ticketmaster");
                });
#pragma warning restore 612, 618
        }
    }
}
